# Generated by Django 3.2.9 on 2022-01-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='Hello World', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='label_job',
            field=models.CharField(blank=True, choices=[('A', 'برنامه نویس اندروید'), ('F', 'برنامه نویس فرانت اند'), ('B', 'برنامه نویس بک اند'), ('D', 'طراحی سایت'), ('S', 'توسعه دهنده سرور'), ('E', 'سایر')], max_length=2, null=True),
        ),
    ]
