# Generated by Django 3.2.9 on 2022-01-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AQ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to=''),
        ),
    ]
