# Generated by Django 3.2.9 on 2022-01-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AQ', '0002_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='ادرس')),
                ('status', models.BooleanField(default=True, verbose_name='ایا نمایش داده شود؟')),
                ('position', models.IntegerField(default=0, verbose_name='پوزیشن')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['position'],
            },
        ),
    ]
