# Generated by Django 3.2.9 on 2022-01-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AQ', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(related_name='questions', to='AQ.Category'),
        ),
    ]
