# Generated by Django 3.2.9 on 2022-02-01 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AQ', '0006_replyanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReplyAnswer',
        ),
    ]
