# Generated by Django 3.2.9 on 2022-02-18 10:05

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AQ', '0009_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='1.jpg', upload_to='', verbose_name='تصویر')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرز',
                'ordering': ['created'],
            },
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['created'], 'verbose_name': 'جواب', 'verbose_name_plural': 'جواب ها'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['created'], 'verbose_name': 'سوال', 'verbose_name_plural': 'سوال ها'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'لایک', 'verbose_name_plural': 'لایک ها'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='متن جواب'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_reply',
            field=models.BooleanField(default=False, verbose_name='پاسخ داده شده؟'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panswers', to='AQ.question', verbose_name='جواب به سوال'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranswers', to='AQ.answer', verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uanswer', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='متن سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(related_name='questions', to='AQ.Category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to='', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='ادرس'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Qvotes', to='AQ.question', verbose_name='سوال'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uvotes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
